### ISSUE TITLE
The named parameter 'theme' isn't defined: flutter_svg 2.0.7 -> 2.0.8 problem

### ISSUE THREAD

**Issue by meg4cyberc4t** [dnfield/flutter_svg#1006]
The named "theme" parameter from the SvgPicture was removed during the last minor update.
In the process of "pub get" my CI stopped.

There is no information about this in breaking changes, there is no major version. This needs to be fixed...

`
[lxp_ithub_theme]:   error - lib\src\components\navigation_bar\lxp_ithub_navigation_bar.dart:139:19 - Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'theme'. - undefined_named_parameter
`

**Comment by meg4cyberc4t** [comment]
+ Information for those who have used Svg Theme to indicate colors in svg, use:
```dart
 colorFilter: ColorFilter.mode(
  pictureColor,
  BlendMode.srcIn,
)
```

**Comment by escamoteur** [comment]
agreed, this is a breaking change, so the Version nunber should have been changes to a new major version

**Comment by dnfield** [comment]
This was an oversight, and just need to add this back in. Sorry about that.

**Comment by dnfield** [comment]
Happened as part of https://github.com/dnfield/flutter_svg/pull/964

**Comment by dnfield** [comment]
Argh. Wait. Reading the code some more.

**Comment by dnfield** [comment]
Yes, the theme parameter moved from the `SvgPicture` to the `SvgLoader` class.

I agree that this was a semver fail on my part. The problem is that the old functionality probably wasn't working the way you thought it was - the `theme` parameter was just getting ignored.

I'd be fine with adding back an `@deprecated SvgTheme? theme` parameter to unbreak people.

**Comment by dnfield** [comment]
2.0.9 fixes this. Maybe should have been 2.0.8+1 but .. oh well.
