### ISSUE TITLE
InputDecoration

### ISSUE THREAD

**Issue by 926** [dnfield/flutter_svg#154]
Hi @dnfield,
Thanks for providing svg package to Flutter.  Yet, I fail to display the svg as an icon : 
Here is what works in *png* : 
    decoration: InputDecoration(labelText: "Telephone", 
    icon: Icon(Icons.phone)),

Here is my attemptin using *svg* : 
    decoration: InputDecoration(labelText: "Whatsapp", 
    icon: ImageIcon(AssetImage(whatsapp))),

With on top : 
    final String whatsapp = 'assets/whatsapp.svg';
    final Widget svgWhatsapp = new SvgPicture.asset(
      whatsapp,
      color: Colors.green,
      semanticsLabel: 'svgWhatsapp'
);

Is this the right way ?

**Comment by dnfield** [comment]
Not directly related, but for your `semanticsLabel` it would be best to pick something that would make sense when read by a screen reader, since that's what users will end up hearing when they highlight it :)

I think rather than using `ImageIcon` you want to just directly use `SvgPicture.asset` for the `icon` property.  I'm not sure I fully understand the use case though.  What's the problem you're seeing?

**Comment by 926** [comment]
@dnfield thanks so much for lightspeed reply,
It works : 
decoration: InputDecoration(labelText: "Whatsapp", icon: SvgPicture.asset(whatsapp)),

The use case is that the imported .svg icon will render nice on any screen size.

I did not understand that this package also made .svg talk ? Is it onLongHold ?

**Comment by dnfield** [comment]
If you go to your accessibility settings and turn on the screen reader.  It's not specific to this package

**Comment by dnfield** [comment]
AFAICT this isn't a bug and isn't needed.  Please feel free to comment or open a new issue if this isn't actually resolved!
