### ISSUE TITLE
depends on flutter_svg >=0.13.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by ahmedali91** [dnfield/flutter_svg#160]

**Comment by dnfield** [comment]
What are you using that depends on 0.13.0?

You probably want 0.12.4.  You can dependency override to that in the worst case scenario.   0.13.0 uses some cutting edge error reporting features that are not available in earlier versions.  The only reason I migrated it is to support clients on master (and soon, dev).

**Comment by AlexVincent525** [comment]
@dnfield Flutter 1.5.9 has been reverted, so I think this update may remove or revert too? 😢

**Comment by dnfield** [comment]
It hasn't been reverted.  1.5.9-pre.94 is a version that only exists on master right now.  Flutter's versioning for this means "94 commits after 1.5.8".

The next dev version of Flutter (which should be coming any day now) will contain 1.5.9-pre.94 (either as 1.5.9 itself, or as 1.6.0).

flutter_svg 0.13.0 should _only_ be used by someone on master right now - it does not make sense for most consumers yet.  However, flutter_svg 0.12.4 and below _will not work on Flutter master anymore_ because of a breaking change that happened at the commit corresponding to 1.5.9-dev.94 (specifically, flutter/flutter@63aa5b3647dbd912a02f7545fc0101003cb3adc4).

For some time now until this lands on stable, I'll try to keep patches applied to both the 0.12.x (which will work on stable/beta), and 0.13.x (which will work on master now and dev soon).

**Comment by dnfield** [comment]
You can see the diff between 0.12.14 and 0.13.0 here: https://github.com/dnfield/flutter_svg/compare/stable...master

The changes are:

 - Use the new error API (this is the breaking change) which will lead to better results when debugging using IntelliJ and the Web inspector (and I presume VSCode).
- Use the new const constructor on `Rect`
- Use set literals

None of this has any impact on parsing or rendering.

**Comment by AlexVincent525** [comment]
Yep and this commit makes 10~20 packges on pub failed on master.
Anyway thank you for stay with the latest.

**Comment by dnfield** [comment]
I'm not sure I understand - what's failing right now on master?

**Comment by AlexVincent525** [comment]
With the DiagnosticsNode came out, which referenced to pre.108. See this: https://github.com/flutter/flutter/issues/31962

**Comment by dnfield** [comment]
Ahhh I understand now.  Yes unfortunately there didn't seem to be a good way to make this not be breaking, but it will make debugging much better

**Comment by AlexVincent525** [comment]
We are not discussing the same commit, but what I want to say is those commit recently made.flutter's error reporting API very unstable, so we can just wait when the breaking changes accepted by most of people, or just like now: bring up a new version or new branches to adapt with the new APIs. :smile:

**Comment by theArtechnology** [comment]
It took me quite some time to understand, but just for others:
To fix the issue, you have to switch from dev branch to master branch.
To do so, use this command
```
flutter channel master
```
When you are done, do this:
```
flutter upgrade
```

**Comment by dnfield** [comment]
This should no longer be the case on dev.  It is still the case on beta for now

**Comment by theArtechnology** [comment]
So, it's a ** temporary fix** then! Thanks for pointing out and thanks a lot for this flutter plugin, works smoothly as expected for me!

**Comment by egementrk** [comment]
> It took me quite some time to understand, but just for others:
> To fix the issue, you have to switch from dev branch to master branch.
> To do so, use this command
> 
> ```
> flutter channel master
> ```
> 
> When you are done, do this:
> 
> ```
> flutter upgrade
> ```

It's works on me
