### ISSUE TITLE
Wrong display on android

### ISSUE THREAD

**Issue by gstaykov** [dnfield/flutter_svg#191]
I'm using the following code to display svg logo in my app:
```
SvgPicture.asset(
          'assets/images/Logo_white.svg',
          width: 200.0,
        )
```
But it looks different on Android and IOS (the IOS version is the correct one. I know it looks the opposite but it is because I'm testing things. You can get the original svg file here: https://we.tl/t-uOs5hJebJo)

IOS:
<img width="431" alt="Screenshot 2019-07-07 at 18 06 50" src="https://user-images.githubusercontent.com/23344972/60770277-0cd74b80-a0e2-11e9-8cf5-b570faac0f49.png">

Anroid:
<img width="398" alt="Screenshot 2019-07-07 at 18 03 57" src="https://user-images.githubusercontent.com/23344972/60770278-0cd74b80-a0e2-11e9-8433-3e2c3e976bd8.png">

The bug is that on Android there are extra spaces between the letters and the crosshair

Version:
flutter_svg: ^0.12.0

Original SVG file:
https://we.tl/t-uOs5hJebJo

**Comment by dnfield** [comment]
I'd guess that you're missing the font on Android, and you're only getting it on iOS because it's installed on your system and you're testing with a simulator.

You could try bundling the correct font in with your application, although even then you may find slight variations from platform to platform on font/text rendering.  Your best bet is probably to vectorize the font glyphs into SVG paths if you want to avoid bundling the font and dealing with platform variations.

**Comment by gstaykov** [comment]
There is no text widget.Evrything is in the svg. This is link to the svg https://we.tl/t-uOs5hJebJo

**Comment by dnfield** [comment]
The SVG uses text. The "Zetr" are in there as text with the font Kefa.

**Comment by gstaykov** [comment]
Ok i see. Maybe you are right. However I already made the logo out of text widget and SVGpicture.asset  only for the crosshair icon. Thanks for your support. I hope my case helped you too. Nice library. Cheers

**Comment by dnfield** [comment]
In that case maybe youc an just remove this part from your SVG:

```svg
          <g id="Zetr" font-family="Kefa-Bold, Kefa" font-size="48" font-weight="bold">
                <text>
                    <tspan x="0" y="45">Zetr</tspan>
                </text>
            </g>
```
