### ISSUE TITLE
Improve plugin for beginners

### ISSUE THREAD

**Issue by Rockvole** [dnfield/flutter_svg#24]
Ideas to improve the plugin for beginners :
1. Include details in the getting started description stating that the svg must be drawn inside a sized widget to be visible.
OR
2. In the getting started description, include what is needed to make the example work right away. e.g. wrap the example in a SizedBox. (Had me stumped for hours)
OR
3. Include an error message stating that the svg will not be displayed because it has no size (no information was shown when my image did not appear).
OR
4. Display black/yellow chevrons (like the flutter image library) on screen if it cannot be displayed.
OR
5. Dont require the svg to be put in a SizedBox, but allow the width / height parameters as arguments.

P.S. Your plugin is excellent work, I just hope for a few tweaks :)

**Comment by dnfield** [comment]
You're not the first one to be a bit confused by the sizing.  I think a good compromise is to have some optional parameters for width and height - if they're specified, use a SizedBox witht hose dimensions, otherwise size to parent.  

Your other suggestions are tougher - it may be intended  to render the SVG offstage for some reason, or to initially render it with no height and width to get it cached.

**Comment by Rockvole** [comment]
I tried to type width and height as soon as I used the SvgPicture.file(), so that would be clear enough I think.

**Comment by dnfield** [comment]
Changes for this are now in master, should go with next version.

**Comment by Rockvole** [comment]
I tried the new version with width and height and it worked well. Thanks.
