### ISSUE TITLE
Delay in loading svg from assets

### ISSUE THREAD

**Issue by nikhil097** [dnfield/flutter_svg#244]
While loading svg images from assets stored in the project locally, there is a considerable delay in loading the image which gives the feel like we are loading the image from Internet.

**Comment by dnfield** [comment]
There are a number of things that could cause slowness here - a device with a bad SD card, or the complexity of the SVG are likely causes (a very complex SVG might be taking so long to render that your time to load from network or disk are inconsequential).

It would be helpful to get some timing for the various parts here - i.e. using the same methods to load the SVG from disk or network that this library uses and comparing, and how long it's taking to render the SVG from a simple string.

I'm going to close this for now - if you have more details to add and it turns out there's a bug in this library, we can re-open.

**Comment by minhvuongrbs** [comment]
Right. I also has the same issue with the SVG image that is only 12KB in size.

**Comment by andreidiaconu** [comment]
@dnfield I see you closed the issue, but I think we should at least consider our options. We are seeing noticeable delays with more complex svg files and this might become a good enough reason to stop using the library. Is there any kind of caching, pre-rendering, etc that we can try?

**Comment by dnfield** [comment]
There's a precachePicture API

**Comment by andreidiaconu** [comment]
Yup, I found out after I wrote the comment. It does improve our use-case quite a bit, so we will try to leverage that.
Thank you.

**Comment by totalerex** [comment]
I confirm that issue exists, my solution was to precache ALL svgs in memory, only after that I got smooth route animations.
