### ISSUE TITLE
Ellipse not drawn correctly

### ISSUE THREAD

**Issue by Rockvole** [dnfield/flutter_svg#28]
Hi Dan,
In this image the circle around the squares is squashed.

https://github.com/Rockvole/communikate20-kbml/blob/master/images/descriptive_quantity/more.svg

**Comment by dnfield** [comment]
Looks like a bug in the Ellipse parsing logic.  I never noticed it before because my ellipse visual tests were of __just__ an ellipse, and even though it was scaled down from what it was supposed to be it was less obvious.

This is a pretty easy fix.  At this point, it's looking like the next version will require the latest flutter beta FYI.

**Comment by dnfield** [comment]
Fixed in 6162cd2 

Thanks for these by the way - please keep them coming, it'll keep improving the library!

**Comment by dnfield** [comment]
Published in v0.5.0
