### ISSUE TITLE
Is version 0.18.0 safe (stable) to use?

### ISSUE THREAD

**Issue by gabrielginter** [dnfield/flutter_svg#373]
I noticed there is a new version 0.18.0 but is not clear in the changelog what's new and the test says "failed". So I was wondering if it's safe to use.

![image](https://user-images.githubusercontent.com/13461933/86256474-911fba00-bbe2-11ea-9f79-9b141d7af7ed.png)

Thanks

**Comment by andcea** [comment]
It also doesn't seem to work with the Flutter stable channel.
`depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.`

**Comment by dnfield** [comment]
Pub does not have the minimum required version of Flutter yet for v0.18.0. 

It is safe to use as long as you meet the minimum version, and in fact if you're using that version of Flutter or greater you must use v0.18.0 - otherwise stick with 0.17.x.

There are customers of this package who need to be on later versions of Flutter. Unfortunately it causes a lot of confusion while the versions propagate.

**Comment by gabrielginter** [comment]
Understood, @dnfield thanks for the information, although new people who find this package will have issues and might give up on it, would be a shame, being such a good package to have. Perhaps add some info on the README.md file for newcomers.

thanks again

**Comment by dnfield** [comment]
I agree this is unfortunate - but it should resolve itself fairly soon. I'll check with the pub folks on when pub gets updated.
