### ISSUE TITLE
Detect unhandled elements

### ISSUE THREAD

**Issue by IchordeDionysos** [dnfield/flutter_svg#473]
@dnfield is it possible in a dry-run to detect if all parts in a SVGs are supported yet? 🤔
The idea is to prevent uploads of broken SVG files in an internal tool built on Flutter.

What I was thinking about is using the [`svgPictureStringDecoder`](https://pub.dev/documentation/flutter_svg/latest/svg/Svg/svgPictureStringDecoder.html) and then detecting if any errors occur.

Looking at the source code I've found the [`_unhandledElement` variable](https://github.com/dnfield/flutter_svg/blob/f2a180642019f503cbe4b542c1b89e74fd584227/lib/src/svg/parser_state.dart#L17), which is filled, but never accessed.
It's currently, only used for throwing errors once per entry, but the library doesn't do anything else with it. (We would also have to track unhandled XML properties)

How hard would it be to report these kinds of warnings as part of the PictureInfo?
Also, would it also work for the web? I guess so, because we only parse the SVG, but not render it yet?
https://github.com/dnfield/flutter_svg/issues/173#issuecomment-503901756

**Comment by dnfield** [comment]
Right now that unhandledElements set is just to avoid repeatedly printing error messages. 

This is handled by `print` today: https://github.com/dnfield/flutter_svg/blob/f2a180642019f503cbe4b542c1b89e74fd584227/lib/src/svg/parser_state.dart#L912. I'd be open to a patch that adds some kind of hook to notify a test, or adds an option to make that throw rather than print.

**Comment by IchordeDionysos** [comment]
@dnfield I opened a PR about detecting unhandled elements :)
