### ISSUE TITLE
This is the only package has lot's of problems with flutter stable version

### ISSUE THREAD

**Issue by coditori** [dnfield/flutter_svg#490]
Whenever I want to back to the stable I find out > flutter_svg says you must use the latest flutter SDK and this is not good. Any package should consider "backward compatibility".

**Comment by dnfield** [comment]
There are version(s) published on pub.dev that are compatible with stable. I will try, in the future, to avoid publishing non-dev tagged versions that are incompatible with stable. I must admit, I will probably get this wrong at times though because it's not super easy for me to keep track of. I really wish that pub version solving worked better for this though. It's difficult though because Flutter doesn't use semver.
