### ISSUE TITLE
SVGs to Flutter Custom Paint Code

### ISSUE THREAD

**Issue by amorenew** [dnfield/flutter_svg#493]
I found the following tool to convert SVG to custom paint code
I share it so it could be an alternative
https://fluttershapemaker.com/

**Comment by dnfield** [comment]
Cool. I'd be happy to add this to the readme as an alternative if the author would like.

**Comment by amorenew** [comment]
@dnfield I created a PR
https://github.com/dnfield/flutter_svg/pull/494

**Comment by dnfield** [comment]
Mentioned this in the PR I just opened, but on a couple SVGs I just tried this tool produces pretty questionable output. I'm also a bit concerned about the design model here - having a web service rather than e.g. a codegen solution is probably harder to deal with to make sure your code stays in sync with what the designer gives you. I'm still fine with linking it though.

**Comment by dnfield** [comment]
The code it produces will also have trouble because it ends up doing lots of work in the paint phase and doesn't cache anything.

**Comment by amorenew** [comment]
@dnfield Author mentioned that he will make static variables to improve the performance.
Still, the tool is not perfect but I think it is a cool idea

**Comment by amorenew** [comment]
@dnfield I approved your PR, Send me the Dash bird :)
