### ISSUE TITLE
it is possible to generate the svg by "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0.... data ?

### ISSUE THREAD

**Issue by ralinres** [dnfield/flutter_svg#679]

**Comment by dnfield** [comment]
Yes.

If you're _only_ targetting the HTML backend on web, you can just dump that into an `Image` widget and it will magically work. I don't recommend this since you're likely not _only_ targetting HTML web.

Otherwise, you can use `base64.decode` from `dart:convert` to decode the substring after `data:image/svg+xml;base64,`, and then feed that into `SvgPicture.string`.

If this can be avoided it should be. It will be inefficient to do the base64 decode on device. If this file is an asset you should decode it before building your app. If it's a network thing, you should see if you can get your server to provide the actual XML string rather than a base64 encoded version of it.
