### ISSUE TITLE
Performance issues examples.

### ISSUE THREAD

**Issue by modulovalue** [dnfield/flutter_svg#752]
Hello Dan,

Quote from https://github.com/flutter/flutter/issues/1831:

> [...] It works reasonably well, but has some performance issues that I have not been able to overcome and that I think are inherent to a combination of the SVG specification, XML, and limitations Flutter currently has around dynamic shader compilation.

I wanted to ask if you could share some examples that made you reach that conclusion.

**Comment by dnfield** [comment]
Some of this is getting addressed in a new package - https://github.com/dnfield/vector_graphics.

Here are a few problems:

- You end up UTF-8 decoding an asset that many not even have any text/strings in it that you care about. This happens on the UI thread.
- You end up XML parsing a document structure when you really just want a series of drawing commands. This takes extra memory and a significant amount of CPU time.
- SVG path data must be parsed from a string to a series of numbers that have rules requiring backreferences and many allocations. Arc commands must be decomposed to cubics before they're really usable (even if you use Skia's `arcTo` methods, they're going to do it for you). 
- SVG allows you do to wild and crazy things, so editors produce SVGs that do it. For example:
  - Nesting groups unnecessarily
  - Applying random transforms and then undoing them later with another transform.
  - Applying masks or clips unnecessarily, which are expensive at runtime even if they make no visual difference.
  - Defining graphical elements out of order in the document (requires additional memory for storage and resolution).
  - Arbitrary use of raster elements is less than ideal and can lead to unexpected memory usage/performance improvements or degredations. I've seen SVGs submitted to this repo that are _exclusively_ composing several PNG images.
  - The SVG spec went nuts on text and supporting everything it expects to do there is super expensive.
  - The SVG spec went nuts on graphical filtering - there are at least 10 different ways to produce a drop shadow and all of them are more expensive than a simple drop shadow primitive, which is almost exclusively what they get used for.
- "Full" support requires HTML, JS, and CSS. Even if you say "ok no HTML or JS," there's no getting around at least a little CSS support. Full CSS support is challenging and expensive. Less than full gets complaints from customers.
- Most existing SVG optimization programs (excepting now vector_graphics_compiler, which was created for this purpose) only optimize for binary size. They do not optimize for runtime rendering performance or memory usage. 

vector_graphics uses a binary format that can often be parsed in <1ms where the SVG it was generated from can take >100ms. And it can elide certain expensive operations now so that getting to the first frame of rasterization is faster.

**Comment by modulovalue** [comment]
Thank you for the detailed response.
