### ISSUE TITLE
Render failed on vmware ubuntu 22.04

### ISSUE THREAD

**Issue by 21pages** [dnfield/flutter_svg#815]
```
<svg viewBox="0 0 448 512"><path d="M0 93.7l183.6-25.3v177.4H0V93.7zm0 324.6l183.6 25.3V268.4H0v149.9zm203.8 28L448 480V268.4H203.8v177.9zm0-380.6v180.1H448V32L203.8 65.7z" fill="white" />

```

**Comment by dnfield** [comment]
I'm unable to reproduce this - although flutter_svg won't complain right now, your svg is technically invalid because it's missing a closing tag.

I'd recommend retrying to render this without using white as the fill color, it's possible you're not seeing this because you're rendering it on a white background.
