### ISSUE TITLE
This SVG schema not working

### ISSUE THREAD

**Issue by mescarpenter** [dnfield/flutter_svg#851]
Recently I saw some SVG's not working, the component loading an empty file. While searching possible error I find a concrete schema not showing nothing. Any idea?

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="2133" height="2133" viewBox="0 0 2133 2133">
  <image id="Capa_1" data-name="Capa 1" y="103" width="2133" height="1939" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAACFUAAAeTCAYAAACAIIo4AAAgAElEQVR4nOzdz2+k933Y8S9F27EsOTsCBLgO4pgqjALGJPG4KFBggkgjPL2bOqXFcxAXqA59gELcXnrc3UtPBchF0QcF9kDq8PjgC6k/YLCjy94KUWiZRRokGiOBndSLeLaNYcfuSsVDfUfhrpbcITk/nh+vF7DgWrAk8vNdkZzhez7ftQAAAAAAADVXZMlGCGHjqY9i8JyPahx/nXaU5sOJPw8AAJREFQAAAAAAVF6RJb0YTZRvr8W3nfh2UY5CCJP466P49uSvpfnwyJ8aAIDmE1UAAAAAAFApRZYM4paJ750KKapoGl18EDdeHIktAACaRVQBAAAAAMBKFVmyGUJ4I4YUVQ0oLuIo/iq3W4yEFgAA9SWqAAAAAABgq...29XiMpCwkYIUS56Im52InXUgogZgDBZyN/pQxQnpntpFH9/mb45IcS2SNgIIdKIhksKIb6Imf1/v1CwBe3keE0AAAAASUVORK5CYII="/>`
  
File: 
![cup](https://user-images.githubusercontent.com/78363407/218062649-bc1a60c6-1cb3-425f-b8fa-0fa8c947e919.svg)

**Comment by dnfield** [comment]
The fragment you shared isn't valid SVG - it is missing at the least a closing tag.

When I fix that and paste it into chrome, it looks pretty much like what you're showing - a very highly scaled and blurry image.

I'm really not sure what this bug is looking for, but feel free to add more details and I'll reopen if it's a bug in this library.
