### ISSUE TITLE
Adding new entry to the cache throws an exception when the max cache size is reached

### ISSUE THREAD

**Issue by vase4kin** [dnfield/flutter_svg#863]
Hi, 

When the cache reaches the max capacity it throws an exception:
```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: 'package:flutter_svg/src/cache.dart': Failed assertion: line 104 pos 14: '_cache.length < maximumSize': is not true.
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      Cache._add (package:flutter_svg/src/cache.dart:104:14)
#3      Cache.putIfAbsent.<anonymous closure> (package:flutter_svg/src/cache.dart:89:9)
#4      _rootRunUnary (dart:async/zone.dart:1406:47)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

I was able to reproduce it in the widget tests and in the running app (debug). 
the version is 2.0.1, the flutter version is 3.7.3.

**Comment by pro100andrey** [comment]
Hi @vase4kin, you should set `maximumSize` for fix this, example:
```dart
import 'package:flutter_svg/flutter_svg.dart';
svg.cache.maximumSize = 1000;
```

Thanks!

**Comment by Maatteogekko** [comment]
@pro100andrey that may be a workaround, but why is the assertion there in the first place?
It works fine in release (without the assertion)

**Comment by pro100andrey** [comment]
@Maatteogekko yes, this is a workaround, I don't have time to create pull request and make tests.
In my opinion the problem is an incorrect check point for remove first object from cache if `_cache.length == maximumSize && maximumSize > 0` for async `pendingResult`.  But I can be wrong :)

```dart
Future<ByteData> putIfAbsent(
    Object key,
    Future<ByteData> loader(),
  ) {
    assert(key != null); // ignore: unnecessary_null_comparison
    assert(loader != null); // ignore: unnecessary_null_comparison
    Future<ByteData>? pendingResult = _pending[key];
    if (pendingResult != null) {
      return pendingResult;
    }

    ByteData? result = _cache[key];
    if (result != null) {
      // Remove the provider from the list so that we can put it back in below
      // and thus move it to the end of the list.
      _cache.remove(key);
    } else {
      // For fix, need move code from here

      // if (_cache.length == maximumSize && maximumSize > 0) {
      //   _cache.remove(_cache.keys.first);
      // }
      pendingResult = loader();
      _pending[key] = pendingResult;
      pendingResult.then((ByteData data) {
        

       // to here
        if (_cache.length == maximumSize && maximumSize > 0) {
          _cache.remove(_cache.keys.first);
        }



        _pending.remove(key);
        _add(key, data);

        result = data; // in case it was a synchronous future.
      });
    }
    if (result != null) {
      _add(key, result!);
      return SynchronousFuture<ByteData>(result!);
    }
    assert(_cache.length <= maximumSize);
    return pendingResult!;
  }
```

**Comment by Maatteogekko** [comment]
Actually I think the issue lies with [this line](https://github.com/dnfield/flutter_svg/blob/c19005297fb78d49d5737e60bb1f4229812a0e20/lib/src/cache.dart#L91).

If you have a synchronous future you end up calling `_add` two times. This does not break anything because the `key` and `data` are the same both of the times, but the assertion fails on the second call.
- we are at max capacity and need to add another element (100 elements in cache)
- remove the first element (99 elements in cache)
- insert a new element (100 elements in cache)
- insert again the same element (assertion fails)

I am not sure why `result = data; // in case it was a synchronous future.` exists, but just removing it solves the double add for my case. Probably not the solution, but may point in the right direction
