### ISSUE TITLE
Path On Click

### ISSUE THREAD

**Issue by ekremkenter** [dnfield/flutter_svg#89]
Is it possible to implement on click listener to paths? I am trying to implement a word map with paths of countries and path xml contains country code as id so there should be 2 features,
- [ ] Get tapped path
- [ ] Change filling of clicked path

I can contribute if it needs to be implemented.

Example path:
```xml
<path id="AD" title="Andorra" class="land" d="M480.487,331.376L480.41,331.401L480.152,331.556L480.005,331.61L479.871,331.637L479.766,331.626L479.708,331.535L479.714,331.396L479.69,331.272L479.67,331.205L479.708,331.024L479.794,330.927L479.913,330.847L480.101,330.876L480.499,330.992L480.582,331.101L480.583,331.173L480.51,331.292z"/>
```

Final implementation in flutter should be something like [here](https://www.amcharts.com/visited_countries/)

**Comment by dnfield** [comment]
I don't plan to support this.  There are a lot of strange edge cases that would get really tough to handle properly, and at this point you'd be better off not trying to implement it all using SVG.

I'd recommend instead trying to use some combination of https://pub.dartlang.org/packages/built_path with `ClipPath` widgets - or just otherwise preprocessing the path data (that package is a little fiddly right now and build_runner with flutter is kind of counter-intuitive).

**Comment by ekremkenter** [comment]
Thanks for the recommendation @dnfield I will try to do so.

**Comment by dnfield** [comment]
You could use Path.transform.  it would probably be good to do that as part of the build step but that's not implemented yet.

**Comment by raiyan24r** [comment]
> @dnfield I managed to show countries with build_path combined with ClipPath. Thanks a million! But I have a problem with sizes, my path changes from 0 to 1000 and to draw those correctly I need to have a container with 1K width / height. Is there a quick way to shrink that to a smaller container maybe with some zooming?

Hey! I needed to implement the same thing.Would you mind sharing the repository or source code?I am really having a hard time over this
