### ISSUE TITLE
[Suggestion] Un-deprecate `color` and `colorBlendMode`.

### ISSUE THREAD

**Issue by PhiFry** [dnfield/flutter_svg#952]
I dont really see a reason as to why they were deprecated and IMO creating custom `ColorFilter` with specified `BlendMode` (which me and Im sure many others have no idea what they are) is just annoying.

I can see in the source code that color is used and still working:
```dart
colorFilter = colorFilter ?? _getColorFilter(color, colorBlendMode),
```
Usually in the framework when you find contradictory parameters there are asserts preventing conflicts.

# Suggestion

Remove the deprecated flag on `color` and `colorBlendMode` and add an assertion:
```dart
assert(
  colorFilter == null || color == null,
   'You can only pass colorFilter or color, not both.',
)
```

Example of this in the standard library `ListView`:
```dart
assert(
  itemExtent == null || prototypeItem == null,
  'You can only pass itemExtent or prototypeItem, not both.',
),
```

**Comment by Evoswork** [comment]
I support it, it only increased the useless code

**Comment by dnfield** [comment]
I've discussed this elsewhere and now can't find the bug. There are multiple reasons to not do this:

- Without the ability to specify the color filter, I get bugs from confused users who really want a matrix based color filter but can't figure out how to get it to work with a blend mode (because it could never work with a blend mode, it's just not what they want).
- Having the ability to specify three different conflicting properties adds to cognitive overhead in the API and runtime-only errors that are not lintable currently. We could request a lint from Dart, but honestly I think it's a poor API design to include multiple exclusive parameters on a method/constructor.
- It is trivial to provide a blend-mode based color filter, and it is _better for developers to understand what they're asking for_. Doing a blend based color filter of an SVG is often not cheap (especially for larger/complex drawings), and especially when you could have used a `ColorMapper` instead (e.g. to trivially change a black icon to a red or green one or whatever).

**Comment by steowens** [comment]
100% deprecating Color.value is absolutely insane especially since there is no easy way to save color value off to SavedPreferences when you remove it entirely.
